export const typeToKoreanName = {
  word: '낱말',
  sentence: '짧은 글',
  paragraph: '긴 글',
};

export const keyboardButton = {
  backspace: 8,
  tab: 9,
  clear: 12,
  enter: 13,
  shift: 16,
  control: 17,
  alt: 18,
  pauseBreak: 19,
  capsLock: 20,
  hanjaMode: 25,
  esc: 27,
  spacebar: 32,
  pageUp: 33,
  pageDown: 34,
  end: 35,
  home: 36,
  arrowLeft: 37,
  arrowUp: 38,
  arrowRight: 39,
  arrowDown: 40,
  insert: 45,
  delete: 46,
  windows: 91,
  f1: 112,
  f2: 113,
  f3: 114,
  f4: 115,
  f5: 116,
  f6: 117,
  f7: 118,
  f8: 119,
  f9: 120,
  f10: 121,
  f11: 122,
  f12: 123,
  numLock: 144,
  scrollLock: 145,
  koreanLanguage: 229,
};

export const prohibitedKeyCodeList = [
  keyboardButton.tab,
  keyboardButton.clear,
  keyboardButton.control,
  keyboardButton.alt,
  keyboardButton.pauseBreak,
  keyboardButton.capsLock,
  keyboardButton.hanjaMode,
  keyboardButton.esc,
  keyboardButton.pageUp,
  keyboardButton.pageDown,
  keyboardButton.end,
  keyboardButton.home,
  keyboardButton.arrowLeft,
  keyboardButton.arrowUp,
  keyboardButton.arrowRight,
  keyboardButton.arrowDown,
  keyboardButton.insert,
  keyboardButton.delete,
  keyboardButton.windows,
  keyboardButton.f1,
  keyboardButton.f2,
  keyboardButton.f3,
  keyboardButton.f4,
  keyboardButton.f5,
  keyboardButton.f6,
  keyboardButton.f7,
  keyboardButton.f8,
  keyboardButton.f9,
  keyboardButton.f10,
  keyboardButton.f11,
  keyboardButton.f12,
  keyboardButton.numLock,
  keyboardButton.scrollLock,
];

export const prohibitedParagraphKeyCodeList = [
  keyboardButton.clear,
  keyboardButton.capsLock,
  keyboardButton.control,
  keyboardButton.alt,
  keyboardButton.pauseBreak,
  keyboardButton.hanjaMode,
  keyboardButton.esc,
  keyboardButton.pageUp,
  keyboardButton.pageDown,
  keyboardButton.end,
  keyboardButton.home,
  keyboardButton.arrowLeft,
  keyboardButton.arrowUp,
  keyboardButton.arrowRight,
  keyboardButton.arrowDown,
  keyboardButton.insert,
  keyboardButton.delete,
  keyboardButton.windows,
  keyboardButton.f1,
  keyboardButton.f2,
  keyboardButton.f3,
  keyboardButton.f4,
  keyboardButton.f5,
  keyboardButton.f6,
  keyboardButton.f7,
  keyboardButton.f8,
  keyboardButton.f9,
  keyboardButton.f10,
  keyboardButton.f11,
  keyboardButton.f12,
  keyboardButton.numLock,
  keyboardButton.scrollLock,
];
